### PR TITLE
Add LICENSE file

### PR DESCRIPTION
**Pull request by kevinetienne**
The `setup.py` should be updated to reflect it, and the trove classifiers should be set.

### CODE REVIEW

**Comment by kevinetienne** [comment]
@meshy can you review please

**Comment by meshy** [comment]
Also needs `license` added to `setup.py` [similar to this](https://github.com/django/django/blob/1.7/setup.py#L43)

**Comment by meshy** [comment]
`__version__` and `get_version` should be removed from the `__init__`

**Comment by kevinetienne** [comment]
Thanks, forgot to save my change for `version`

**Comment by kevinetienne** [comment]
Updated

**Comment by meshy** [comment]
:+1:

**Pull request merged**
